apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-deployment
spec:
  selector:
    matchLabels:
      name: pet-clinic
  template:
    metadata:
      labels:
        name: pet-clinic
    spec:
      containers:
      - name: pet-clinic
        image: myenvpractise.jfrog.io/eks-docker-local/spring-petclinic:initial-commit
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: artcloud1cred
